intent_file: intent.md
continuity_file: continuity.md
thermostat:
  chaos_ratio_target: 0.5
  lower_bound: 0.35
  upper_bound: 0.65
motif_budget: 7
semci:
  threshold: 80
  weights:
    coherence: 0.3
    tension: 0.3
    readability: 0.2
    voice: 0.2
medici_nodes: [3, 9, 15, 22]
required_tags: [desire, fear, cost]
freeze_tags:
  acte_i: vActeI
  acte_ii: vActeII
  acte_iii: vActeIII
reader_loop:
  device: kindle
  cadence: monthly
